# -*- coding: utf-8 -*-
"""dr1e.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VALBHRmqmV-I2nL6_YiO5A52XVktqY-6
"""

!pip install tensorflow==2.12.0 opencv-python==4.8.0.76

!pip install ultralytics opencv-python numpy supervision deep-sort-realtime

import torch
import cv2
import numpy as np
import supervision as sv
from ultralytics import YOLO
from deep_sort_realtime.deepsort_tracker import DeepSort
from google.colab import drive
from IPython.display import display, Image, clear_output

# Mount Google Drive
drive.mount('/content/drive')

# Load YOLOv8 Model
yolo_model = YOLO("yolov8x.pt")  # Use "yolov8s.pt" for better accuracy

# Load DeepSORT Tracker
tracker = DeepSort(max_age=30)

# Video Path (Update this with your actual video path)
video_path = "/content/drive/MyDrive/military.mp4"

#Object Detection + Tracking
def detect_and_track(video_path):
    cap = cv2.VideoCapture(video_path)

    if not cap.isOpened():
        print(" Error: Cannot open video file.")
        return

    frame_count = 0

    try:
        while cap.isOpened():
            ret, frame = cap.read()
            if not ret:
                break

            frame_count += 1

            # running YOLO object detection
            results = yolo_model(frame)

            # Extract detected objects
            detections = []
            for result in results:
                for box in result.boxes:
                    x1, y1, x2, y2 = map(int, box.xyxy[0])  # Bounding box
                    conf = float(box.conf[0])  # Confidence score
                    cls = int(box.cls[0])  # Class ID

                    if conf > 0.5:  # Only consider confident detections
                        detections.append(([x1, y1, x2 - x1, y2 - y1], conf, cls))

            # Running DeepSORT tracker
            tracks = tracker.update_tracks(detections, frame=frame)

            # Draw Bounding Boxes and Track IDs
            for track in tracks:
                if not track.is_confirmed():
                    continue

                x, y, w, h = map(int, track.to_tlbr())  # Convert to top-left-bottom-right
                track_id = track.track_id
                label = f"ID {track_id}"

                # Draw bounding box
                cv2.rectangle(frame, (x, y), (x + w, y + h), (0, 255, 0), 2)
                cv2.putText(frame, label, (x, y - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.6, (0, 255, 0), 2)

            # Convert frame to RGB for Colab display
            frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

            # Save frame & display in Colab
            cv2.imwrite('/content/frame.jpg', frame_rgb)
            clear_output(wait=True)
            display(Image('/content/frame.jpg'))

            # Press 'q' to stop manually
            if cv2.waitKey(1) & 0xFF == ord('q'):
                break

    except KeyboardInterrupt:
        print("Stopped by user.")
    finally:
        cap.release()

# 🚀 Step 8: Run Detection & Tracking
detect_and_track(video_path)